# Generated by Django 2.2 on 2020-08-31 18:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, help_text='Other information', null=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('displayUrl', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('downloadUrl', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('owner', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_owner', to='people.PersonPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
