# Generated by Django 2.2.12 on 2020-08-06 17:40

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('talk_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('talk_title', models.CharField(blank=True, max_length=32, null=True)),
                ('talk_path', models.CharField(blank=True, max_length=256, null=True)),
                ('talk_url', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('talk_displayUrl', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('talk_downloadUrl', models.URLField(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True)),
                ('talk_comments', wagtail.core.fields.StreamField([('e_comment', wagtail.core.blocks.StructBlock([('comment_owner', wagtail.core.blocks.PageChooserBlock(help_text='Owner of the comment', null=True, page_type=['person.PersonFormPage'], required=False)), ('comment_datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=False)), ('comment_message', wagtail.core.blocks.TextBlock(help_text='Other information', null=True, required=False))], icon='fa-id-badge', null=True))], null=True)),
            ],
        ),
    ]
