# Generated by Django 2.2 on 2020-09-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='displayUrl',
            new_name='display_url',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='downloadUrl',
            new_name='download_url',
        ),
    ]
