# Generated by Django 2.2 on 2020-09-08 19:58

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20200902_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='owner',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='people.PersonPage'),
        ),
    ]
