# Generated by Django 2.2 on 2020-09-09 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_auto_20200908_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
