# Generated by Django 2.2.12 on 2020-08-10 09:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_auto_20200809_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLanguageStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unkown', max_length=255, null=True)),
                ('color', models.CharField(default='Unkown', max_length=255, null=True)),
                ('insertions', models.IntegerField(default='Unkown', null=True)),
                ('deletions', models.IntegerField(default='Unkown', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTransitionStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertions', models.IntegerField(default='Unkown', null=True)),
                ('deletions', models.IntegerField(default='Unkown', null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('cid', models.CharField(max_length=255, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unkown', max_length=255, null=True)),
                ('username', models.CharField(default='Unkown', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('codelanguages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codelanguages', to='enterprise.CodeLanguageStatistic')),
                ('codetransition', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codetransition', to='enterprise.CodeTransitionStatistic')),
                ('feed', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_feed', to='enterprise.ContributionFeed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='feed_section',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='history_section',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='languages_section',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='overview_tab_name',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='project_tab_name',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='projects_section',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='users_section',
        ),
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='users_tab_name',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unkown', max_length=255, null=True)),
                ('url', models.URLField(blank=True, default='Unkown', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='Unkown', null=True)),
                ('owner_name', models.CharField(blank=True, default='Unkown', max_length=255, null=True)),
                ('owner_username', models.CharField(blank=True, default='Unkown', max_length=255, null=True)),
                ('owner_email', models.EmailField(blank=True, default='Unkown', max_length=254, null=True)),
                ('codelanguages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codelanguages', to='enterprise.CodeLanguageStatistic')),
                ('codetransition', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codetransition', to='enterprise.CodeTransitionStatistic')),
                ('contributors', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_contributor', to='enterprise.Contributor')),
                ('feed', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_feed', to='enterprise.ContributionFeed')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opsprojects', to='enterprise.EnterpriseFormPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epcontributor', to='enterprise.EnterpriseFormPage'),
        ),
        migrations.CreateModel(
            name='ContributionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertions', models.IntegerField(null=True)),
                ('deletions', models.IntegerField(null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('raw_changes', models.TextField(max_length=255, null=True)),
                ('feed', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epfeed2', to='enterprise.EnterpriseFormPage')),
            ],
        ),
        migrations.AddField(
            model_name='contributionfeed',
            name='files',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='files', to='enterprise.ContributionFile'),
        ),
        migrations.AddField(
            model_name='contributionfeed',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epfeed', to='enterprise.EnterpriseFormPage'),
        ),
    ]
