# Generated by Django 2.2.12 on 2020-08-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_personformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personindex',
            name='introduction',
        ),
    ]
