# Generated by Django 2.2.12 on 2020-08-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial_data'),
        ('person', '0007_auto_20200807_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'ordering': ('date_joined',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.snekuser',),
        ),
    ]
