# Generated by Django 2.2 on 2020-09-01 13:14

from django.db import migrations
import esite.colorfield.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('name', wagtail.core.blocks.CharBlock(max_length=255)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255)), ('owner', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('fullname', wagtail.core.blocks.CharBlock(max_length=255)), ('name', wagtail.core.blocks.CharBlock(max_length=255))])), ('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz')), ('fullname', wagtail.core.blocks.CharBlock(max_length=255)), ('name', wagtail.core.blocks.CharBlock(max_length=255))]))), ('languages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', esite.colorfield.blocks.ColorBlock()), ('name', wagtail.core.blocks.CharBlock(max_length=255)), ('size', wagtail.core.blocks.IntegerBlock()), ('share', wagtail.core.blocks.FloatBlock())])))]))], blank=True, default=None, null=True),
        ),
    ]
