# Generated by Django 2.2 on 2020-09-01 19:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200901_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='current_statistic',
            field=wagtail.core.fields.StreamField([('statistic_year', wagtail.core.blocks.StructBlock([('calendar_3d', wagtail.images.blocks.ImageChooserBlock()), ('calendar_2d', wagtail.core.blocks.TextBlock()), ('contribution_type_2d', wagtail.core.blocks.TextBlock()), ('total_issue_contributions', wagtail.core.blocks.IntegerBlock()), ('total_commit_contributions', wagtail.core.blocks.IntegerBlock()), ('total_repository_contributions', wagtail.core.blocks.IntegerBlock()), ('total_pull_request_contributions', wagtail.core.blocks.IntegerBlock()), ('total_pull_request_review_contributions', wagtail.core.blocks.IntegerBlock()), ('total_repositories_with_contributed_issues', wagtail.core.blocks.IntegerBlock()), ('total_repositories_with_contributed_commits', wagtail.core.blocks.IntegerBlock()), ('total_repositories_with_contributed_pull_requests', wagtail.core.blocks.IntegerBlock()), ('current_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock()), ('end_date', wagtail.core.blocks.DateBlock()), ('total_days', wagtail.core.blocks.IntegerBlock()), ('total_contributions', wagtail.core.blocks.IntegerBlock())])), ('longest_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock()), ('end_date', wagtail.core.blocks.DateBlock()), ('total_days', wagtail.core.blocks.IntegerBlock()), ('total_contributions', wagtail.core.blocks.IntegerBlock())]))]))], blank=True, null=True),
        ),
    ]
