# Generated by Django 2.2 on 2020-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200903_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_link',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
