# Generated by Django 2.2 on 2020-09-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20200903_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='avatar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.SNEKPersonAvatarImage'),
        ),
    ]
