# Generated by Django 2.2 on 2020-09-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20200903_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_link',
            name='link_type',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram Post'), ('PHOTO', 'Photo URL'), ('YOUTUBE', 'Youtube URL'), ('VIMEO', 'VIMEO URL'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
