# Generated by Django 2.2 on 2020-09-10 08:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20200906_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='current_statistic',
            field=wagtail.core.fields.StreamField([('statistic_year', wagtail.core.blocks.StructBlock([('calendar3d', wagtail.images.blocks.ImageChooserBlock(required=False)), ('calendar2d', wagtail.core.blocks.TextBlock(required=False)), ('contribution_type2d', wagtail.core.blocks.TextBlock()), ('total_issue_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_commit_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repository_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_review_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_issues', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_commits', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_pull_requests', wagtail.core.blocks.IntegerBlock(required=False)), ('current_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('longest_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('busiest_day', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('total', wagtail.core.blocks.IntegerBlock(required=False))]))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_statistic',
            field=wagtail.core.fields.StreamField([('statistic_year', wagtail.core.blocks.StructBlock([('calendar3d', wagtail.images.blocks.ImageChooserBlock(required=False)), ('calendar2d', wagtail.core.blocks.TextBlock(required=False)), ('contribution_type2d', wagtail.core.blocks.TextBlock()), ('total_issue_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_commit_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repository_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_review_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_issues', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_commits', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_pull_requests', wagtail.core.blocks.IntegerBlock(required=False)), ('current_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('longest_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('busiest_day', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('total', wagtail.core.blocks.IntegerBlock(required=False))]))]))], blank=True, null=True),
        ),
    ]
