# Generated by Django 2.2 on 2020-09-10 18:11

from django.db import migrations
import esite.colorfield.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20200910_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organisations',
            field=wagtail.core.fields.StreamField([('organisation', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('name', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.core.blocks.TextBlock(required=False)), ('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('username', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))), ('projects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('name', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('owner', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('username', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('username', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))), ('languages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', esite.colorfield.blocks.ColorBlock()), ('name', wagtail.core.blocks.CharBlock(max_length=255)), ('size', wagtail.core.blocks.IntegerBlock()), ('share', wagtail.core.blocks.FloatBlock())])))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('name', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('owner', wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('username', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('avatar_url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', required=False)), ('fullname', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('username', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))), ('languages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', esite.colorfield.blocks.ColorBlock()), ('name', wagtail.core.blocks.CharBlock(max_length=255)), ('size', wagtail.core.blocks.IntegerBlock()), ('share', wagtail.core.blocks.FloatBlock())])))]))], blank=True, null=True),
        ),
    ]
