# Generated by Django 2.2 on 2020-09-10 22:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20200910_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='display_image_gallery',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='personpage',
            name='display_music_gallery',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='personpage',
            name='display_video_gallery',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='meta_link',
            name='link_type',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram Post'), ('SOUNDCLOUD', 'Soundcloud Song'), ('PHOTO', 'Photo URL'), ('YOUTUBE', 'Youtube URL'), ('VIMEO', 'VIMEO URL'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_statistic',
            field=wagtail.core.fields.StreamField([('statistic_year', wagtail.core.blocks.StructBlock([('calendar3d', wagtail.images.blocks.ImageChooserBlock(required=False)), ('calendar_data', wagtail.core.blocks.TextBlock(required=False)), ('contribution_type_data', wagtail.core.blocks.TextBlock()), ('total_issue_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_commit_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repository_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_review_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_issues', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_commits', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_pull_requests', wagtail.core.blocks.IntegerBlock(required=False)), ('current_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('longest_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('busiest_day', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('total', wagtail.core.blocks.IntegerBlock(required=False))]))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_statistic',
            field=wagtail.core.fields.StreamField([('statistic_year', wagtail.core.blocks.StructBlock([('calendar3d', wagtail.images.blocks.ImageChooserBlock(required=False)), ('calendar_data', wagtail.core.blocks.TextBlock(required=False)), ('contribution_type_data', wagtail.core.blocks.TextBlock()), ('total_issue_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_commit_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repository_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_pull_request_review_contributions', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_issues', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_commits', wagtail.core.blocks.IntegerBlock(required=False)), ('total_repositories_with_contributed_pull_requests', wagtail.core.blocks.IntegerBlock(required=False)), ('current_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('longest_streak', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock(required=False)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('total_days', wagtail.core.blocks.IntegerBlock(required=False)), ('total_contributions', wagtail.core.blocks.IntegerBlock(required=False))])), ('busiest_day', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('total', wagtail.core.blocks.IntegerBlock(required=False))]))]))], blank=True, null=True),
        ),
    ]
