# Generated by Django 2.2 on 2020-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20200911_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='display_contribution_types',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='personpage',
            name='display_week_activity',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
