# Generated by Django 2.2.12 on 2020-08-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200809_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='snekuser',
            name='sources',
            field=models.TextField(null=True),
        ),
    ]
