# Generated by Django 2.2.12 on 2020-08-11 17:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(blank=True, max_length=250, null=True)),
                ('platformUrl', models.CharField(blank=True, max_length=250, null=True)),
                ('avatarUrl', models.CharField(blank=True, max_length=250, null=True)),
                ('websiteUrl', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('createdAt', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('statusMessage', models.CharField(blank=True, max_length=250, null=True)),
                ('statusEmojiHTML', models.CharField(blank=True, max_length=250, null=True)),
                ('bids', models.TextField(blank=True, null=True)),
                ('tids', models.TextField(blank=True, null=True)),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='people.PersonFormPage')),
            ],
        ),
    ]
