# Generated by Django 2.2 on 2020-08-31 18:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('instagram', 'Instagram')], max_length=255, null=True)),
                ('person_page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='people.PersonPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
