# Generated by Django 2.2 on 2020-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
