# Generated by Django 2.2 on 2020-08-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='source_url',
            field=models.URLField(null=True),
        ),
    ]
