# Generated by Django 2.2 on 2020-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_profile_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='source_type',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('INSTAGRAM', 'Instagram')], max_length=255, null=True),
        ),
    ]
