# Generated by Django 2.2 on 2020-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200901_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_access_token_expired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
