# Generated by Django 2.2 on 2020-09-02 11:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0006_auto_20200902_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, help_text='Comment text', null=True)),
                ('author', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='people.PersonPage')),
                ('reply_to', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
