# Generated by Django 2.2 on 2020-08-31 18:21

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('comment', '0001_initial'),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='people.PersonPage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='talk',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_talk', to='talk.Talk'),
        ),
    ]
