# Generated by Django 2.2.12 on 2020-08-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='imprint_tab_name',
        ),
    ]
