# Generated by Django 2.2.12 on 2020-08-11 17:40

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionfeed',
            name='files',
            field=modelcluster.fields.ParentalManyToManyField(related_name='files', to='enterprises.ContributionFile'),
        ),
    ]
