# Generated by Django 2.2 on 2020-08-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_auto_20200821_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='sources',
        ),
        migrations.AlterField(
            model_name='enterpriseformpage',
            name='enterprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_page', to='enterprises.Enterprise'),
        ),
    ]
