# Generated by Django 2.2.12 on 2020-08-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_remove_enterpriseformpage_imprint_tab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseformpage',
            name='settings_tab_name',
        ),
    ]
