# Generated by Django 2.2 on 2020-09-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_snekpersonavatarimage'),
        ('enterprises', '0003_auto_20200826_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseformpage',
            name='avatar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.SNEKImage'),
        ),
    ]
