# Generated by Django 2.2.12 on 2020-08-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationformpage',
            options={'verbose_name': 'Registration Form Page'},
        ),
    ]
