# Generated by Django 2.2.12 on 2020-08-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200805_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormField',
            new_name='RegistrationFormField',
        ),
    ]
