# Generated by Django 2.2.12 on 2020-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_personindex_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='personformpage',
            name='bids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personformpage',
            name='tids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
