# Generated by Django 2.2.12 on 2020-08-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personformpage',
            options={'verbose_name': 'Person Form Page'},
        ),
    ]
