# Generated by Django 2.2 on 2020-09-07 10:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0005_snekpersonavatarimage'),
        ('people', '0012_auto_20200906_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, help_text='Other information', null=True)),
                ('points', models.IntegerField(default=0)),
                ('collectors', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='achievements', to='people.PersonPage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.SNEKImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
