# Generated by Django 2.2 on 2020-08-21 11:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('images', '0003_snekachievementimage'),
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='collectors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='achievements', to='people.PersonFormPage'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.SNEKImage'),
        ),
    ]
